name: json_render
description: JSON Web Render Framework
version: 1.0.1
homepage: https://github.com/gmpassos/json_render

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  intl: "^0.16.0"
  mercury_client: ^1.0.6
    #path: ../mercury_client
  dom_tools: ^1.0.0
    #path: ../dom_tools

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
