name: json_render
description: JSON Web Render Framework - Automatically renders a JSON tree using rich components.
version: 2.0.1
homepage: https://github.com/gmpassos/json_render

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  mercury_client: ^2.0.1
  dom_tools: ^2.0.1
  swiss_knife: ^3.0.5
  chart_engine: ^2.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8

#dependency_overrides:
#  mercury_client:
#    path: ../mercury_client
#  dom_tools:
#    path: ../dom_tools
#  swiss_knife:
#    path: ../swiss_knife
#  chart_engine:
#    path: ../chart_engine

