name: json_render
description: JSON Web Render Framework
version: 1.2.7
homepage: https://github.com/gmpassos/json_render

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  intl: "^0.16.0"
  mercury_client: ^1.1.4
    #path: ../mercury_client
  dom_tools: ^1.2.7
    #path: ../dom_tools
  swiss_knife: ^2.3.9
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
