name: json_render
description: JSON Web Render Framework - Automatically renders a JSON tree using rich components.
version: 1.3.4
homepage: https://github.com/gmpassos/json_render

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  intl: "^0.16.0"
  mercury_client: ^1.1.8
    #path: ../mercury_client
  dom_tools: ^1.3.4
    #path: ../dom_tools
  swiss_knife: ^2.5.5
    #path: ../swiss_knife
  chart_engine: ^1.1.3
    #path: ../chart_engine

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
