name: json_render
description: JSON Web Render Framework - Automatically renders a JSON tree using rich components.
version: 2.0.5
homepage: https://github.com/gmpassos/json_render

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  intl: ^0.18.0
  mercury_client: ^2.1.7
  dom_tools: ^2.1.9
  swiss_knife: ^3.1.3
  chart_engine: ^2.0.5

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  dependency_validator: ^3.2.2

#dependency_overrides:
#  mercury_client:
#    path: ../mercury_client
#  dom_tools:
#    path: ../dom_tools
#  swiss_knife:
#    path: ../swiss_knife
#  chart_engine:
#    path: ../chart_engine

