name: json_render
description: JSON Web Render Framework - Automatically renders a JSON tree using rich components.
version: 2.1.0
homepage: https://github.com/gmpassos/json_render

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  intl: ^0.19.0
  mercury_client: ^2.2.1
  dom_tools: ^2.3.0
  swiss_knife: ^3.2.0
  chart_engine: ^2.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  dependency_validator: ^3.2.3

#dependency_overrides:
#  mercury_client:
#    path: ../mercury_client
#  dom_tools:
#    path: ../dom_tools
#  swiss_knife:
#    path: ../swiss_knife
#  chart_engine:
#    path: ../chart_engine

